title: AI Generated Blog Test
email: yiming.song09@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog. This is where I share my thoughts and ideas.
baseurl: ""
url: "https://ysong233.github.io/"
theme: minima
permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown
kramdown:
  input: GFM
